image: rocker/verse

before_script:
  #- apt-get update && apt-get -y install pandoc pandoc-citeproc r-base
  - R -e "install.packages(c('data.table', 'rasterVis', 'sf'))"

pages:
  script:
    - R -e "bookdown::render_book('index.Rmd', output_format = 'all', output_dir = 'public')"
  artifacts:
    paths:
      - public
  only:
    - master
