image: rocker/verse

before_script:
  - apt-get -y update && apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
  - R -e "install.packages(c('data.table', 'raster', 'rasterVis', 'sf', 'units', 'reactable'))"

pages:
  script:
    - R -e "bookdown::render_book('index.Rmd', output_format = 'all', output_dir = 'public')"
  artifacts:
    paths:
      - public
  only:
    - master
