image: debian:buster-slim

before_script:
  - apt-get update && apt-get -y install pandoc pandoc-citeproc r-base
  - R -e "install.packages(c('bookdown', 'ggplot2', 'data.table'))"

pages:
  script:
    - R -e "bookdown::render_book('', output_dir = 'public')"
  artifacts:
    paths:
      - public
  only:
    - master
