image: debian:buster-slim

before_script:
  - apt-get update && apt-get -y install pandoc r-base
  - R -e "install.packages('bookdown')"

pages:
  script:
    - R -e "bookdown::render_book('')"
  artifacts:
    paths:
      - _book
  only:
    - master
