# (PART) Analysis {-}

# data.table

**TODO: ALR basic resources, and grab from slides**

## .SD
https://cran.r-project.org/web/packages/data.table/vignettes/datatable-sd-usage.html



## Slides {#dt-slides}
Workshop: Introduction to data.table

Date: November 16 2017

[Slides](https://slides.robitalec.ca/intro-data-table.html) and [Resources](https://gitlab.com/robit.a/workshops/-/archive/master/workshops-master.zip?path=intro-data-table)

```{r, echo = FALSE}
knitr::include_url('https://slides.robitalec.ca/intro-data-table.html')
```


# Social Network Analysis

## Examples

**TODO: more examples**

[SocCaribou/Social Network Analysis](https://github.com/wildlifeevoeco/SocCaribou/blob/master/scripts/4-SocialNetworkAnalysis.R)


## Packages

### `spatsoc`

Alec, Quinn and Eric developed `spatsoc`, an R package for generating social networks from GPS data. 

Resources:

* [blog post](https://ropensci.org/blog/2018/12/04/spatsoc/)
* repository: [ropensci/spatsoc](https://github.com/ropensci/spatsoc/)
* vignettes, documentation: [docs.ropensci.org/spatsoc](https://docs.ropensci.org/spatsoc/)
* paper: [Conducting social network analysis with animal telemetry data: Applications and methods using spatsoc](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13215)
* [CSTWS webinar](https://slides.robitalec.ca/CSTWS-webinar-spatsoc.html)


### `hwig`

Alec developed `hwig`, an R package for calculating gregariousness adjusted half-weight index.

* repository: [robitalec/hwig](https://github.com/robitalec/hwig)


## Slides {#sna-slides}

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRMzDEm8bkxbERxRummBcgqHzOb2vLasEgJNsNC8r462hANEUCwu4dxDyVkdmroFCK7HFsIkhawKe_t/embed?start=false&loop=false&delayms=3000" frameborder="0" width="480" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>


# Behavioural Reaction Norms
## Slides {#brn-slides}

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTPmfrBj_WyLSq6AhmTXrAwxGDNzve3F7Dhgwr-01m9yU7WE2tDLttT-18MXrxTyg/embed?start=false&loop=false&delayms=3000" frameborder="0" width="480" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>





# Earth Engine
**TODO: ALR link to ee best practices, ee developers docs, your repo of scripts**

# Cool Packages {#analysis-cool}

**TODO: organize into spatial/ plotting/ helper/ etc**

## Data frames / tables / sheets
* [`googlesheets4`](https://googlesheets4.tidyverse.org/)



## Dates and times
* [`anytime`](https://github.com/eddelbuettel/anytime) 

## Spatial packages


* [`parzer`](https://github.com/ropensci/parzer) parsing geographic coordinates


https://ropensci.org/packages/
