---
output:
	bookdown::gitbook:
		base_format: xarigan::moon_reader
number_sections: false
---

# Slides

## Past workshops
### Git and Projects

Date: February 6 2020

[Slides](https://slides.robitalec.ca/git-and-projects.html) and  [Resources](https://slides.robitalec.ca/git-and-projects/git-and-projects.zip)

```{r, echo = FALSE}
knitr::include_url('https://slides.robitalec.ca/git-and-projects.html')
```

### Basic R Markdown
Date: October 21 2019

[Slides](https://slides.robitalec.ca/basic-rmd.html) and  [Resources](https://slides.robitalec.ca/basic-rmd/basic-rmd.zip)

```{r, echo = FALSE}
knitr::include_url('https://slides.robitalec.ca/basic-rmd.html')
```


### Developing R Packages
Date: October 25 2018

[Slides](https://slides.robitalec.ca/r-packages.html) and   [Resources](https://slides.robitalec.ca/r-packages/r-packages.zip)

```{r, echo = FALSE}
knitr::include_url('https://slides.robitalec.ca/r-packages.html')
```


### Functions in R
Date: October 25 2018

[Slides](https://slides.robitalec.ca/functions-in-r.html) and  [Resources](https://slides.robitalec.ca/functions-in-r/functions-in-r.zip)

```{r, echo = FALSE}
knitr::include_url('https://slides.robitalec.ca/functions-in-r.html')
```

### Introduction to data.table
Date: November 16 2017

[Slides](https://slides.robitalec.ca/intro-data-table.html) and  [Resources](https://slides.robitalec.ca/intro-data-table/intro-data-table.zip)

```{r, echo = FALSE}
knitr::include_url('https://slides.robitalec.ca/intro-data-table.html')
```

### Introduction to ggplot2
Date: November 2 2017

[Slides](https://slides.robitalec.ca/intro-ggplot.html) and  [Resources](https://slides.robitalec.ca/intro-ggplot/intro-ggplot.zip)

```{r, echo = FALSE}
knitr::include_url('https://slides.robitalec.ca/intro-ggplot.html')
```

